server:
  port: 80
  servlet:
    context-path: /
spring:
  thymeleaf:
    servlet:
      content-type: text/html
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8

